mod_version = 2.0.2
mod_name = Compact Tools
mod_id = compacttools73
mod_authors = Bowser_The_Boss
mod_licence = All Rights Reserved
mod_group_id = xyz.quazaros
mod_description=Combines all tools into one

version_control = https://github.com/UY-scuti73/Compact_Tools-Mod
discord_link = https://discord.gg/zHzFgWX8KW