mod_version = 2.0.5
mod_name = CompactTools
mod_id = compacttools73
mod_authors = Bowser_The_Bosss
mod_licence = All Rights Reservedd
mod_group_id = xyz.quazaros
mod_description=Combines all tools into onee